# Aliases for some of the most popular characters.

# Written by hand.

ALIASES = {"Ororo Munroe": "Storm (Ororo Munroe)",
           "Scott Summers": "Cyclops (Scott Summers)",
           "James Howlett": "Wolverine (James Howlett)",
           "Piotr Rasputin": "Colossus (Piotr Rasputin)",
           "Kurt Wagner": "Nightcrawler (Kurt Wagner)",
           "Samuel Guthrie": "Cannonball (Samuel Guthrie)",
           "Katherine Pryde": "Shadowcat (Kitty Pryde)",
           "Charles Xavier": "Professor X (Charles Xavier)",
           "Rahne Sinclair": "Wolfsbane (Rahne Sinclair)",
           "Roberto Da Costa": "Sunspot (Roberto da Costa)",
           "Warren Worthington III": "Angel (Warren Worthington III)",
           "Henry McCoy": "Beast (Henry McCoy)",
           "Danielle Moonstar": "Mirage (Danielle Moonstar)",
           "Robert Drake": "Iceman (Bobby Drake)",
           "Illyana Rasputina": "Magik (Illyana Rasputina)",
           "Sean Cassidy": "Banshee (Sean Cassidy)",
           "Warlock (Technarch)": "Warlock",
           "Alexander Summers": "Havok (Alexander Summers)",
           "Nathan Summers": "Cable (Nathan Summers)",
           "Elizabeth Braddock": "Psylocke (Betsy Braddock)",
           "Tabitha Smith": "Boom-Boom (Tabitha Smith)",
           "Moira MacTaggert (Earth-TRN748)": "Moira MacTaggert",
           "Max Eisenhardt": "Magneto (Max Eisenhardt)",
           "Rachel Summers (Earth-811)": "Rachel Summers",
           "Julio Richter": "Rictor (Julio Richter)",
           "Alison Blaire": "Dazzler (Alison Blaire)",
           "Amara Aquilla": "Magma (Amara Aquilla)",
           "Russell Collins": "Rusty Collins",
           "Brian Braddock": "Captain Britain (Brian Braddock)",
           "Lorna Dane": "Polaris (Lorna Dane)",
           "Sally Blevins": "Skids",
           "Douglas Ramsey": "Cypher (Douglas Ramsey)",
           "Raven Darkhölme": "Mystique (Raven Darkhölme)",
           "Sebastian Shaw": "Black King (Sebastian Shaw)",
           "Xi'an Coy Manh": "Karma (Xi'an Coy Manh)",
           "Frederick Dukes": "Blob",
           "Arthur Maddicks": "Artie Maddicks",
           "Emma Frost": "White Queen (Emma Frost)",
           "Katherine Pryde (Earth-811)": "Widget",
           "St. John Allerdyce": "Pyro",
           "Carol Danvers": "Binary (Carol Danvers)",
           "Patricia Tilby": "Trish Tilby",
           "Jubilation Lee": "Jubilee (Jubilation Lee)",
           "James Proudstar": "Warpath (James Proudstar)",
           "Christopher Summers": "Corsair (Christopher Summers)",
           "En Sabah Nur": "Apocalypse (En Sabah Nur)",
           "New York City Police Department": "N.Y.P.D.",
           "Irene Adler": "Destiny (Irene Adler)",
           "Remy LeBeau": "Gambit (Remy LeBeau)",
           "Dominikos Petrakis": "Avalanche",
           "Cain Marko": "Juggernaut (Cain Marko)",
           "Vanessa Carlysle": "Copycat (Vanessa Carlysle)",
           "Jimaine Szardos": "Amanda Sefton",
           "Frank Bohannan": "Crimson Commando",
           "Jason Wyngarde": "Mastermind (Jason Wyngarde)",
           "Maria Callasantos": "Feral",
           "Victor Creed": "Sabretooth (Victor Creed)",
           "David Haller": "Legion (David Haller)",
           "Manuel de la Rocha": "Empath (Manuel de la Rocha)",
           "Theresa Cassidy": "Siryn (Theresa Cassidy)",
           "Rita Wayword": "Spiral",
           "James Madrox": "Multiple Man (James Madrox)",
           "Martin Fletcher": "Super Saber",
           "Thomas Cassidy": "Black Tom Cassidy",
           "Yuriko Oyama": "Lady Deathstrike (Yuriko Oyama)",
           "Mark Hallett": "Sunder",
           "Alice MacAllister": "Malice (Alice MacAllister)",
           "Plague": "Pestilence (Plague)",
           "Eleanor Murch": "Nanny",
           "Mercedes Knight": "Misty Knight",
           "David Moreau": "Genegineer",
           "Autumn Rolfson": "Famine (Autumn Rolfson)",
           "Abraham Kieros": "War (Abraham Kieros)",
           "Guido Carosella": "Guido",
           "Louis Hamilton": "Stonewall",
           "Harold Leland": "Black Bishop (Harry Leland)",
           "Cal'syee Neramani": "Deathbird",
           "Philippa Sontag": "Arclight",
           "John Greycrow": "Scalphunter",
           "Haroun ibn Sallah al-Rashid": "Jetstream",
           "Kodiak Noatak": "Harpoon",
           "Strategic Homeland Intervention, Enforcement and Logistics Division": "S.H.I.E.L.D.",
           "Nimrod (Earth-811)": "Nimrod (Earth-811)",
           "Jennifer Stavros": "Roulette",
           "Nathan Summers (Stryfe) (Earth-4935)": "Stryfe (Nathan Summers)",
           "Marie-Ange Colbert": "Tarot",
           "Wade Wilson": "Deadpool (Wade Wilson)",
           "Sharon Smith": "Catseye",
           "Candace Southern": "Candy Southern",
           "Cormick Grimshaw": "Pipeline",
           "Karl Lykos": "Sauron",
           "Robert Kelly": "Senator Robert Kelly",
           "Peter Parker": "Spider-Man (Peter Parker)",
           "Nathaniel Essex": "Mister Sinister (Nathaniel Essex)",
           "Magus (Technarch)": "Magus (Warlock's Father)",
           "Keniuchio Harada": "Silver Samurai",
           "Michael McCain": "Forearm",
           "Nicholas Fury": "Nick Fury",
           "Richard Gill": "Wildside",
           "Gammenon": "Gammenon the Gatherer",
           "Ambient-Energy Dampening Actualization Module Unit Zero (Earth-4935)": "Zero",
           "Shiro Yoshida": "Sunfire (Shiro Yoshida)",
           "Edward Pasternak": "Tower",
           "Kim Il Sung": "Scrambler",
           "Steven Rogers": "Captain America (Steve Rogers)",
           "Reed Richards": "Mister Fantastic",
           "Victor von Doom": "Doctor Doom",
           "Benjamin Grimm": "The Thing",
           "Kevin MacTaggert": "Proteus (Kevin MacTaggert)",
           "Stephen Strange": "Doctor Strange",
           "James Braddock Jr.": "Monarch (James Braddock Jr.)",
           "Wanda Maximoff": "Scarlet Witch (Wanda Maximoff)",
           "Pietro Maximoff": "Quicksilver (Pietro Maximoff)"}